### ISSUE TITLE
В BOM в списке покупок не отмечено твердотельное реле при выборе АС стола отличного от AC 400х250 

### ISSUE THREAD

**Issue by MIOB** [dmitry-sorkin/K3D-VOSTOK#1]
В табличке на листе "покупные изделия" твердотельное реле отмечается только если выбран стол AC 400х250. Насколько я понимаю реле нужно при выборе любого АС стола.

**Comment by dmitry-sorkin** [comment]
Исправил в [https://github.com/dmitry-sorkin/K3D-VOSTOK/commit/b359f4ea0b25733abac577b17e023347205ff314](этом коммите)
