### ISSUE TITLE
Ошибка в модели kls1-as-303-1-2.

### ISSUE THREAD

**Issue by Foxcor** [dmitry-sorkin/K3D-VOSTOK#10]
В модели kls1-as-303-1-2 не хватает частей, на модель самого принтера не влияет, но не красиво)))
![bug1](https://user-images.githubusercontent.com/30261332/135025918-04344a2c-0269-4be9-a79b-57307fc790e7.jpg)

https://grabcad.com/library/kls1-as-303-1-2

**Comment by dmitry-sorkin** [comment]
![изображение](https://user-images.githubusercontent.com/7548036/135117714-335d7f5d-3246-4290-b80b-111218a935fc.png)

У меня всё норм. Возможно, проблема при экспорте/импорте возникла
