### ISSUE TITLE
Console bottom mount of side walls 

### ISSUE THREAD

**Issue by r8d8** [dmitry-sorkin/K3D-VOSTOK#3]
Planning to build printer, and noticed that side walls has console unsupported "tail", where bottom 20x20 mm base profile lies (see attachments). This is pretty fragile part, as in case one will try to lift printer from side and potentially can crack side walls. Besides, edge is to sharp, to hold it in hand with heavy load of printer 
My proposal is to use 60x20mm profile, same as on top of printer, this will allow to extend wall support all the way down. Also it will give flat rigid surface to hold printer from sides. It shouldn't add too much cost  into BOM, and you don't need rebuild mechanics, just extend legs (currently there is 50mm offset, see Fig.1)
 
![Fig. 1)](https://user-images.githubusercontent.com/8018746/131976601-17f16d37-2d74-45cb-9002-db29f54285b1.png)
![Fig. 2](https://user-images.githubusercontent.com/8018746/131976603-c1a12971-514c-451f-b022-3762949a4f4e.png)

**Comment by dmitry-sorkin** [comment]
It isn't unsupported. There is blind joint in the end of each profile. I will add blind joints to assembly later, when whole frame will be tested.

**Comment by r8d8** [comment]
Got it, thanks.
