### ISSUE TITLE
Примечания к покупным изделиям в БОМ

### ISSUE THREAD

**Issue by Kest430** [dmitry-sorkin/K3D-VOSTOK#38]
в БОМ на листе Покупные изделия есть несколько позиций, ссылки на которые ведут на лоты, где есть выбор необходимого товара/размера/типа. Но не указано, какой именно товар/размер/тип нужно заказать.

Чтобы было меньше вопросов желательно указать примечания.

- **Винт Tr8x2**. Не указано какой нужен шаг резьбы. В чате об этом были вопросы.
- **Гайка POM Tr8x2**. Не указано какой нужен шаг резьбы
- **Концевик механический**. В чате на мой вопрос вы написали, что надо с закругленной на конце лапкой (Arc Lever)

**Comment by dmitry-sorkin** [comment]
У винта и гайки указана резьба Tr8x2 - это однозаходная трапецеидальная резьба с шагом и ходом 2мм. Четырёхзаходная резьба обозначается Tr8x8 (P2). 
Касательно концевика - укажем тип
