### ISSUE TITLE
Баги держателей катушек

### ISSUE THREAD

**Issue by DeltaDesignRus** [dmitry-sorkin/K3D-VOSTOK#39]
1. В детали V05-06-01-01-02 - Inner spool holder rocker plate v1 уступ не позволяет повернуть эту деталь на такой угол, который позволяет деталь V05-06-01-02 - Inner spool holder mount part A v6
![Screenshot 2021-11-16 004323](https://user-images.githubusercontent.com/19409260/141844481-69b10c5e-08a9-4131-9853-9b92217b6e8d.png)
![Screenshot 2021-11-16 004358](https://user-images.githubusercontent.com/19409260/141844485-7b781d0a-a3a4-45ac-ac7f-be9ad4a16387.png)
2. В детали V05-06-01-02 - Inner spool holder mount part A v6(Mirror) нужно убрать пазы под гайки, потому что туда удобнее вставлять винты, которые притянутся к профилю через пазовые гайки.
![Screenshot 2021-11-16 004931](https://user-images.githubusercontent.com/19409260/141844983-1e04214c-37b6-485f-b8e8-844fbabbd1fe.png)
3. Подшипники имеют свободный ход, отчего собранный держатель жидковат.
![Screenshot 2021-11-16 005234](https://user-images.githubusercontent.com/19409260/141845316-b016c54b-c2ae-43d3-8c72-670ab4f4412e.png)
4. Крепление роликов к подшипникам сейчас на трении, либо придется клеить подшипники. Как вариант сделать, как я (модель в чате кидал)
![Screenshot 2021-11-16 005509](https://user-images.githubusercontent.com/19409260/141845520-6657962d-29ca-48a0-99f5-ade6551b90a5.png)
5. Ролики можно сделать не цилиндрическими, а в виде бочонков (с радиусом). Должно дополнительно помочь центрировать катушки.

**Comment by Dimyc** [comment]
Поддерживаю предложения DeltaDesignRus. Нужны какие-то фиксации подшипников, т. к. в данной конструкции при прослаблении размеров держатель разваливается. По п.5 еще хочу добавить, что в ролике желательно добавить упор для подшипника, т. к. если диаметр внутреннего отверстия будет больше диаметра внешней обоймы подшипника, последний соскальзывает с оси опоры и проваливается внутрь отверстия ролика.

**Comment by Dimyc** [comment]
А, уже заметил, что подшипники фиксируются маленькими винтиками. Теперь мысль Соркина понятна. :)

**Comment by Dimyc** [comment]
Погонял я этот держатель и пришел к выводу, что его конструкция не очень хороша для использования типа - отпечатал, собрал и пользуешься. Почему? Не все принтеры настроены для печати с идеальными размерами. Поэтому при сборке будет тяжело добиться соосности установки роликов, т. к. при таких размерах подшипников и при прослаблении размеров не получится установить подшипники без дополнительной фиксации. Это приведет к тому, что либо вся конструкция будет разваливаться при вращении катушки (будут выпадать подшипники из посадочных мест), либо ролики будут крутиться туго или с заеданием. Далее - у большинства будет явно выраженный шов при печати роликов. В совокупности с тугим вращение роликов, прокрутить катушку будет затруднительно. Она будет проскальзывать на шву. При определенном натяжении прутка, не знаю как на CoreXY, но на дрыгостолах еще и голова может немного приподняться. В результате чего появятся вот такие щели на модели (см. фото). Особенно это будет происходить на тяжелых катушках, т.к. пруток уходит вниз и при натяжении он еще сильнее будет зажимать катушку между роликами. Раньше у меня часто были подобные проблемы + слои выкладывались не равномерно. После того как повесил катушку на вал с подшипниками, проблема ушла. Правда появилась новая - приходилось немного подтормаживать катушки, т.к. иногда она по инерции свободно прокручивалась на несколько оборотов. Особенно когда ставил новую катушку. :)

Мне кажется, нужно как-то переделывать держатели под осевое крепления катушки с использование подшипников, например, 608ZZ 8x22x7mm. Rfr 'nj cltkfnm e vtyz gjrf bltq ytn :)

![IMG_20211226_192905](https://user-images.githubusercontent.com/86676790/147416589-3e0bbbc6-87fb-4f1e-ba97-207f05abccf5.jpg)
