### ISSUE TITLE
Разная глубина одного крепежного отверстия в модели правого натяжителя.

### ISSUE THREAD

**Issue by Suhanovd** [dmitry-sorkin/K3D-VOSTOK#4]
![Belt-tensioner-base](https://user-images.githubusercontent.com/51445138/132027154-d410f599-4dc0-4b99-b62a-d74fe73be5c6.jpg)

**Comment by dmitry-sorkin** [comment]
Исправлено в коммите a1267a8983a34ab6f7aff86c4af821e75510018c
