### ISSUE TITLE
Полость в детали V06-01-04-03-01 - Belt tensioner slider (0.5XY)

### ISSUE THREAD

**Issue by MIOB** [dmitry-sorkin/K3D-VOSTOK#44]
<img width="1275" alt="Capture" src="https://user-images.githubusercontent.com/932034/144719892-8884714f-0fb4-49dc-a00d-d535e1a1b32b.PNG">

**Comment by Holyfriend** [comment]
Добавлю, этой детали нет в ПОМ, что очень странно.
