### ISSUE TITLE
Не правильно считается количество шайб М3

### ISSUE THREAD

**Issue by The-Futur1st** [dmitry-sorkin/K3D-VOSTOK#46]
Каждый Roller Assembly содержит 2 шайбы
![image](https://user-images.githubusercontent.com/1551942/145269947-d1ad616b-1532-46b0-980c-3e3644378813.png)
В бом же считается что 4
![image](https://user-images.githubusercontent.com/1551942/145269779-df0f1ec3-44b0-4d56-a9b4-3c113dfb678c.png)
Итого показывает что шайб нужно в 2 раза больше.

**Comment by dms78** [comment]
Вообще нужно даже больше,  так как пространство между двумя средними шайбами забивается тоже шайбами(кто-то печатает проставки)

**Comment by dmitry-sorkin** [comment]
Не актуально так как в версии 0.7 сборки роликов изменены
