### ISSUE TITLE
Проблема с крепежом V05-01-01-02-03 - Belt mount

### ISSUE THREAD

**Issue by Foxcor** [dmitry-sorkin/K3D-VOSTOK#5]
По стандарту DIN 7991 или DIN 965 длина винта идет 16 потом 20 мм. Так вот, 16 мм мало, 20 мм много, упирается в ремень.
![DIN7991-20mm](https://user-images.githubusercontent.com/30261332/132219990-d6756167-43a5-43d2-8762-f451aafc9bd1.jpg)

**Comment by dmitry-sorkin** [comment]
![изображение](https://user-images.githubusercontent.com/7548036/135118915-53892620-ec00-41bb-a3b3-6d35d421f94c.png)
Пока решать вот так. До переделки головы изменять эти детали не буду.

**Comment by dmitry-sorkin** [comment]
Не актуально ввиду временного прекращения поддержки кинематики markforged
