### ISSUE TITLE
V05-01-01-02-03 X axis belt mount предлагается печатать 2шт  для кинематики 0.5XY

### ISSUE THREAD

**Issue by izlat** [dmitry-sorkin/K3D-VOSTOK#54]
При выборе в BOM кинематики 0.5XY деталь для CoreXY - V05-01-01-02-03 - X axis belt mount, предлагается напечатать 2 шт, должно быть 0 шт.

**Comment by dmitry-sorkin** [comment]
Исправлено в версии 0.7
