### ISSUE TITLE
Ошибка в формуле в `K3D-VOSTOK/Docs/BOM v0.6.5-alpha.ods`

### ISSUE THREAD

**Issue by TEH30P** [dmitry-sorkin/K3D-VOSTOK#55]
`BOM v0.6.5-alpha.ods` по адресу `$'Покупные изделия'.C58` битая ссылка в формуле:

`=IFERROR(IFS(#REF!=#REF!,0,#REF!=#REF!,0),1)`

---
И ещё, это конечно не ошибка, и вы, как автор, имеете право меня игнорировать. Но по-моему лучше не делать пробелы в именах файлов, то там то сям это создаёт проблемы. Может лучше перименовать файл в `BOM-v0.6.5-alpha.ods`

**Comment by TEH30P** [comment]
И ещё `$'Покупные изделия'.D29=($Расчёты.B17+50)/1000` тут, по-моему должно быть `$'Покупные изделия'.D29=$Расчёты.B19`. Т.к. +50 это припуск, который настраивается, а не всегда есть. Вообще ячейки `$Расчёты.B16` и `$Расчёты.B17` лишние, в формулах они всё время на 1000 деляться, т.е. повторяют `$Расчёты.B18` и `$Расчёты.B19`.

**Comment by dmitry-sorkin** [comment]
Неактуально ввиду полной переработки BOM в версии 0.7
