### ISSUE TITLE
Not all product items are definitely on AliExpress (Не все позиции однозначно определяются по ссылке на AliExpress)

### ISSUE THREAD

**Issue by petrovi4** [dmitry-sorkin/K3D-VOSTOK#6]
Русское описание ниже 
-----------------
Some links in the BOM to products are described in too general terms. 
Sellers on AliExpress can edit the product, add options that are not compatible with the printer. For example, position 13 in the BOM is called "Fan 5020", and the link leads to a product that has 3 voltage options: 5, 12 and 24 volts. This causes additional confusion and increases the likelihood of an error, although this is easily avoided if we write a full description of the product in the BOM in the name of the product or in the description. 

For example, in position 13, we can add the description "50x20, 24V Centrifugal turbine fan". It will also help to detect and restore dead links to lots that are no longer relevant and are not for sale.

---

Некоторые ссылки в BOM на товары описаны слишком общими терминами. 
Продавцы на AliExpress могут отредактировать товар, добавить опции, которые не совместимы с принтером. Например, позиция 13 в BOM называется "Вентилятор 5020", а ссылка ведет на товар, в котором есть 3 варианта вольтажа: 5, 12 и 24 вольта. Это вызывает дополнительную путаницу и повышает вероятность ошибки, хотя этого легко избежать если в BOM в названии товара или в описании мы напишем полную характеристику товара. 

Например, для позиции 13 мы можем добавить описание "Центробежный турбинный вентилятор 50x20, 24V" что хотя и не однозначно описывает товар (нет бренда, это ничего не говорит о качестве товара), зато указывает на значимые характеристики позиции. Это так же поможет обнаруживать и восстанавливать мертвые ссылки на лоты, которые уже не актуальны и не продаются.

**Comment by petrovi4** [comment]
С удовольствием возьму на себя всю рутину и формально конкретизирую каждую позицию, если Дмитрий в комментарии укажет какие значение для критических характеристик каждой позиции следует использовать. Тот же вентилятор для хотенда я как-то по-умолчанию думал что должен быть 24-х вольтовым, а ссылка на "Вентилятор 30х30х10" (позиция 12) ведет на 12-ти вольтовую версию.

**Comment by dmitry-sorkin** [comment]
Нет необходимости в какой-то конкретизации. Все ссылки даны для примера, в названии позиции указывается вся необходимая информация для его покупки. Если что-то не уточнено, значит это не важно. В случае примера с вентиляторами: рекомендуемые платы имеют выбор напряжения на питание вентиляторов, поэтому не указано какие конкретно брать, это оставляется на усмотрение пользователей.

**Comment by petrovi4** [comment]
Это авторский проект, и, возможно, я тут со своими комментариями как корова в посудной лавке, поэтому заранее прошу прощения :)
Но раз уж проект открытый, то позвольте предложить всё таки существенные для сборки характеристики указывать в BOM'е 

Мой айтишный опыт подсказывает что даже если в случае с тем же вентилятором мы выбирая лот на Али увидели, что продаются варианты 5, 12 или 24 вольта, у нас плата, которая поддерживает выбор напряжения 5, 12 или 24 вольта, то вместо "Вентилятор 5020" все таки лучше будет написать "Вентилятор 5020 - вольтаж любой из следующих: 5/12/24".
Это не сложно, но любого будущего сборщика не ставит в тупик наличие трёх вольтажей на странице лота.
Завтра продавец может добавить четвертый вольтаж, который уже не будет поддерживаться какой-то из плат. И купленный кулер может быть уже не совместим. 
Если что-то может пойти не так - это обязательно случится.
Если пользователь (в данном случае человек, который собирает Восток) может купить что-то не то, или собрать как-то не так - он обязательно это сделает.  Зачем давать такую возможность, если избежать этого так легко?

**Comment by zmeygeruch** [comment]
> Мой айтишный опыт подсказывает что даже если в случае с тем же вентилятором мы выбирая лот на Али увидели, что продаются варианты 5, 12 или 24 вольта, у нас плата, которая поддерживает выбор напряжения 5, 12 или 24 вольта 

Сами по себе 3D принтеры - чисто инженерское устройство. Не для домохозяек. А тут еще и самосбор в альфа версии. Айтишный опыт обычно складывается из отношения юзеров к вашему готовому продукту :) А тут будут собирать люди, которым хотя бы немного понимают в чертежах, схемах, электронике. Достаточно, что там будет вентилятор 5020. Да и, как Дмитрий выше неписал, напряжение у всех может быть разное, а внесение в описание 5/12/24V совершенно никак не сужает круг поиска. :)

**Comment by petrovi4** [comment]
>> Сами по себе 3D принтеры - чисто инженерское устройство. Не для домохозяек.
Почему? Что плохого если 3d принтер будет доступен и для условных домохозяек? Мне кажется, вариант "лучше минимум документации, чтобы только истинные инженеры могли в 3d печать" это огораживание информации, не идущее любой отрасли в плюс. От популяризации, в подавляющем большинстве случаев, выигрывают все.
Я, признаться, не очень хочу обосновать почему "больше документации" лучше чем "меньше документации" (без каких-то предельных, конечно, случаев). Поэтому, так как это всё ещё по духу и по сути - авторский проект, а значит автору единолично принимать решение.
Ещё раз прошу прощения, если моя точка зрения показалась автору навязыванием. Благо, я успел ещё и в чате "поныть" )

**Comment by dmitry-sorkin** [comment]
Доработаю документацию, но после исправления важных косяков

**Comment by dmitry-sorkin** [comment]
Решено в d32101765807e79c6c126dd09d6f5ab5794d603f
