### ISSUE TITLE
Incorrect number of 623 bearings in BOM 0.5.6-alfa / Не верное количество 623 подшипников в BOM 0.5.6-alfa 

### ISSUE THREAD

**Issue by Suhanovd** [dmitry-sorkin/K3D-VOSTOK#7]
Количество подшипников 623zz и f623zz d BOM 8 и 16 соответственно. А на самом деле должно быть 10 и 20, так мест с их установкой 10.
![BOM](https://user-images.githubusercontent.com/51445138/134488671-63746fee-9848-424e-ab7a-893e119fc5eb.jpg)

**Comment by dmitry-sorkin** [comment]
Решено в d32101765807e79c6c126dd09d6f5ab5794d603f
