### ISSUE TITLE
Шкивы в BOM

### ISSUE THREAD

**Issue by DeltaDesignRus** [dmitry-sorkin/K3D-VOSTOK#8]
В BOM в примере, какие шкивы нужно покупать, ссылка на поштучный товар, а он дороже.
Лучше заменить на товар, где в комплекте сразу 3 штуки, дешевле на треть почти, за такие же шкивы.
https://aliexpress.ru/item/32650791423.html

**Comment by dmitry-sorkin** [comment]
В разных комплектациях нужно разное количество шкивов. Поэтому указывать на готовые наборы с определенным количеством некорректно КМК. Позже, если буду делать альтернативные для товаров ссылки, добавлю наборы в альтернативы.
